name: Run CI

on:
  workflow_call:
      
jobs:
  job-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI
        run: echo "Running CI ..."
